apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: patch
  namespace: default  
  description: A collection of all Synapse Entities
  annotations:
    permissions.backstage.io/public-readable: 'true'
spec:
  owner: user:aorudenkiy
  targets:
    - ./backstage-template.yaml

